// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkhuxadeuhhrlamvgpho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5raHV4YWRldWhocmxhbXZncGhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NDQ1NDUsImV4cCI6MjA3MDEyMDU0NX0.QlxGLcrWGRTOErzloDKpNUdgdHmMLYrUbTo0RVwgwqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});